// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq4_A52oafitmvPbN7q-g3FyDPEWjuuC4',
    appId: '1:868969194065:android:f5c1b645d71ab053564e70',
    messagingSenderId: '868969194065',
    projectId: 'dnd-character-manager-80981',
    storageBucket: 'dnd-character-manager-80981.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHXjBBiS21MCwgG-H0wmF9j3gyiVM5YG4',
    appId: '1:868969194065:web:7f6869cec6ee6fb0564e70',
    messagingSenderId: '868969194065',
    projectId: 'dnd-character-manager-80981',
    authDomain: 'dnd-character-manager-80981.firebaseapp.com',
    storageBucket: 'dnd-character-manager-80981.firebasestorage.app',
    measurementId: 'G-Q34EPHMYR3',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHXjBBiS21MCwgG-H0wmF9j3gyiVM5YG4',
    appId: '1:868969194065:web:cb1308a26bb3bc63564e70',
    messagingSenderId: '868969194065',
    projectId: 'dnd-character-manager-80981',
    authDomain: 'dnd-character-manager-80981.firebaseapp.com',
    storageBucket: 'dnd-character-manager-80981.firebasestorage.app',
    measurementId: 'G-6WBBJRG8F2',
  );
}
